### ISSUE TITLE
Reaching Out

### ISSUE THREAD

**Issue by prom3theu5** [Nobody84/Issues_PrismMaui_RegionNavigation#1]
Hey. Don't suppose the issue you have here is related to RegionManagers collection being empty is it, as I'm having something similar occur in latest prerelease (from 10 months ago).

Cheers

**Comment by Nobody84** [comment]
No, 

I just used the wrong interface **INavigatedAware** instead **IRegionAware** in my ViewModels, see [566ac9f](https://github.com/Nobody84/Issues_PrismMaui_RegionNavigation/commit/566ac9ff6cacdc0abec57760d7e067f05dd8e0cf).
